language: python
python:
  - python 3.6
before_install:
  - python --version
  - pip install -U pip
script:
  - coverage run --source=com/dielle/ -m unittest discover;coverage report -m
  - python -m unittest discover